spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        max.in.flight.requests.per.connection: 1

jwt:
  secret: my-256-bit-secret-key-change-this-in-production-please-make-it-long-enough-for-hs256
  expiration: 86400000  # 24 hours

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    com.vanna.restorders: info
    org.springframework.web: INFO
    org.springframework.security: INFO


grpc:
  client:
    inventory-service:
      address: 'static://localhost:9090'
      negotiationType: PLAINTEXT
      deadline: 3s

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10                    
        minimumNumberOfCalls: 5                  
        permittedNumberOfCallsInHalfOpenState: 3 
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s             
        failureRateThreshold: 50                 
        slowCallRateThreshold: 100               
        slowCallDurationThreshold: 2s            
        recordExceptions:
          - io.grpc.StatusRuntimeException       
    instances:
      inventory-service:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: when-authorized
